language: generic
#Super user level permision to execute build
sudo: required
#we need a copy of docker ready to run
services:
  - docker


before_install:
  - docker build -t iaurimas/docker-react -f dockerfile.dev .


#https://facebook.github.io/create-react-app/docs/running-tests#linux-macos-bash
#https://docs.docker.com/engine/reference/run/#env-environment-variables
script:
  - docker run -e CI=true iaurimas/docker-react npm run test

deploy:
  provider: elastikbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "eu-north-1"
  app: "docker-react"
  env: "DockerReact-env"

  #S3 bucket and initial app folder
  bucket_name: "elasticbeanstalk-eu-north-1-860177140429"
  bucket_path: "docker-react"
#Deploy code only when pushed to master
  
